import React from 'react'

const Contact = () => {
  return (
    <div>Contact Us</div>
  )
}

export default Contact

export const metadata = {
    title: "Contact Facebook",
    description: "Generated by create next app",
  };